config/routes.rb
Test2::Application.routes.draw do

  match '/initialise_sell_stock/:id', to: 'sell_stocks#initialise_sell_stock', via: 'get'
  match '/sell_stock', to: 'sell_stocks#sell_stock', via: 'post'
  match '/items/category_update', to: 'items#category_update', via: 'post'
  match '/items/edit_category/:id', to: 'items#edit_category', via: 'get'
  match '/items/list_category', to: 'items#list_category', via: 'get'
  match '/items/create_category', to: 'items#create_category', via: 'post'
  match '/items/new_category', to: 'items#new_category', via: 'get'
  match '/transfer_print', to: 'stocks#transfer_print', via: 'post'
  match '/transfer_comments/:id', to: 'stocks#transfer_comments', via: 'get'
  match '/stock_comments/:id', to: 'stocks#stock_comments', via: 'get'
  match '/alerts_lifecycle', to: 'stocks#alerts_lifecycle', via: 'get'
  match '/calculate_lifecycle_alerts', to: 'stocks#calculate_lifecycle_alerts', via: 'get'
  match '/alerts_minimum', to: 'stocks#alerts_minimum', via: 'get'
  match '/stations_cost', to: 'stocks#stations_cost', via: 'get'
  match '/total_costs', to: 'stocks#total_costs', via: 'get'
  match '/consumables/withdraw/:id', to: 'consumables#withdraw', via: 'get'
  match '/show_stock/:id', to: 'stocks#show_stock', via: 'get'
  match '/issueConsumable', to: 'consumables#issueConsumable', via: 'put'
  match '/consumable_issue/:id', to: 'consumables#consumable_issue', via: 'get'
  match '/station_transfers', to: 'stocks#station_transfers', via: 'get'
  match '/transfers_list', to: 'stocks#transfers_list', via: 'get'
  match '/initialise_transfer_stock/:id', to: 'stocks#initialise_transfer_stock', via: 'get'
  match '/transfer_stock', to: 'stocks#transfer_stock', via: 'post'
  match '/acknowledge_receipt_stock/:id', to: 'stocks#acknowledge_receipt_stock', via: 'get' 
  match '/assets/withdraw_asset/:id', to: 'assets#withdraw_asset', via: 'get'
  match '/assets/issued_list/:id', to: 'assets#issued_list', via: 'get'
  match '/issueAsset', to: 'assets#issueAsset', via: 'put'
  match '/assets/associate_list', to: 'assets#associate_list', via: 'get'
  resources :assets, only: [:destroy]
  match '/assets/issue_asset/:id', to: 'assets#issue_asset', via: 'get'
  match '/asset_list/:id', to: 'assets#asset_list', via: 'get'
  match '/present_stock_update', to: 'stocks#present_stock_update', via: 'put'
  match '/present_stock_edit/:id', to: 'stocks#present_stock_edit', via: 'get'
  match '/stocks/itemList', to: 'stocks#itemList', via: 'get'
  match '/stocks/categoryList', to: 'stocks#categoryList', via: 'get'
  match '/stocks/choice', to: 'stocks#choice', via: 'get'
  match '/associates/list', to: 'associates#list', via: 'get'
  match '/items/redirect', to: 'items#redirect', via: 'get'
  match '/items/list', to: 'items#list', via: 'get'
  resources :regions, :items, :territories, :vendors, :associates, :stocks

  resources :users
  resources :stations
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to:  'static_pages#home'
  
  match '/unassignedUser', to: 'users#assignUserform' ,via: 'get'
  match '/assignLevel', to: 'users#assignLevel' , via: 'put'
  match '/retainLevel/:id', to: 'users#retainLevel' , via: 'delete'
  match '/chooseLevel', to: 'users#chooseLevel' , via: 'get'
  match '/help', to: 'static_pages#help'
  match '/about',to: 'static_pages#about'
  match '/contact',to: 'static_pages#contact'

end

app/models/station.rb
class Station < ActiveRecord::Base
	has_many :users, as: :level, dependent: :nullify
	has_many :associates ,dependent: :restrict
	has_many :stocks, dependent: :restrict
	belongs_to :territory, validate: true
	has_many :items, through: :stocks

	accepts_nested_attributes_for :users
	attr_accessible :nameStation, :territory_id, :addr1, :addr2, :pincode, :contactDetails

	validate :ensure_territory_exist

	validates :nameStation, presence: true, length: {maximum: 30}, uniqueness: true
	validates :territory_id, presence: true
	validates :addr1, presence: true
	validates	:addr2, presence: true
	validates	:pincode, presence: true, numericality: true, length: {is: 6}
	validates :contactDetails, presence: true

	private

		def ensure_territory_exist
			if Territory.find(self.territory_id).nil?
				errors.add(:territory_id, 'Territory')
				false
			else
				true
			end
		end

end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
	before_filter :signed_in_user, only: [:new, :edit,    :index, :create, :update]
	before_filter :admin_user, only: [:new, :update, :edit, :create]

	def update
		@station = Station.find(params[:id])
		if @station.update_attributes(nameStation: params[:nameStation], territory_id: params[:territory_id], addr1: params[:addr1], addr2: params[:addr2], pincode: params[:pincode], contactDetails: params[:contactDetails])
	      flash[:success] = "Territory updated"
	      redirect_to stations_path
	  else
	      render 'edit'
	  end
	end

	def edit
		@station = Station.find(params[:id])
	end

	def new
		@station = Station.new
	end

	def index
		result = user_access_stations(current_user)
		if result == nil
			flash.now[:notice] = "No station assigned to you"
		else
			@stations = result[:stations]
			@name =	result[:name]
		end
	end

	def create
	  @station = Station.new(nameStation: params[:nameStation], territory_id: params[:territory_id], addr1: params[:addr1], addr2: params[:addr2], pincode: params[:pincode], contactDetails: params[:contactDetails])
	  if @station.save
	    flash[:success] = "Successfully added #{@station.nameStation}"
	    redirect_to stations_path
	  else
	    render 'new'
	  end
  end

end

app/helpers/stations_helper.rb
module StationsHelper

	def user_access_stations(user)
		@user_access_stations ||= aux_user_access_stations(user)
	end

	def aux_user_access_stations(user)
		if user[:level_type]!= nil 
			if user.admin?
				@stations = Station.all
				@name = "Central Team" 
			elsif Region.find(user.level_id).nameRegion=="India"
				@stations=Station.all - Region.find_by_nameRegion('Central Team Region').stations
				@name = "India"
			else
				@stations=[]
				if user.level_type == "Region" 
					@stations = Region.find(user.level_id).stations
					@name = Region.find(user.level_id).nameRegion
				elsif user[:level_type] == "Territory"
					@stations = Territory.find(user.level_id).stations
					@name=Territory.find(user.level_id).nameTerritory
				else
					@stations =[Station.find(user.level_id)]
					@name = Station.find(user).nameStation
				end
			end
			{stations: @stations, name: @name}
		else
			nil
		end
	end


	def can_access_station(station)
		if user_access_stations(current_user)[:stations].include? station
			return true
		else
			flash.now[:notice] = "access denied"
			@user = current_user
      render 'users/show'
      return false
    end
  end
end

app/views/stations/edit.html.erb
<% provide(:title, 'Edit Station') %>
<h1>Edit Station</h1>

<div class="row">
  <div class="span4 offset3">
    <%= form_for(@station) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag(:id, @station[:id]) %>
      <%= label_tag(:nameStation, "Station name:") %>
      <%= text_field_tag(:nameStation, @station.nameStation) %>

      <%= label_tag(:territory_id, "Territory:") %>
      <% territory_array = Territory.all.map { |territory| [territory.nameTerritory, territory.id]} %>
      <%= select_tag(:territory_id, options_for_select(territory_array, @station.territory_id)) %>

      <%= label_tag(:addr1, "Address line 1:") %>
      <%= text_field_tag(:addr1, @station.addr1) %>

      <%= label_tag(:addr2, "Address line 2:") %>
      <%= text_field_tag(:addr2, @station.addr2) %>

      <%= label_tag(:pincode, "Pincode:") %>
      <%= text_field_tag(:pincode, @station.pincode) %>

      <%= label_tag(:contactDetails, "Contact Details:") %>
      <%= text_field_tag(:contactDetails, @station.contactDetails) %>


      <%= f.submit "Save changes", class: "btn  btn-primary" %>

  <% end %>

  </div>
</div>

app/views/stations/index.html.erb
<% provide(:title, 'Stations') %>
<h1>Stations</h1>

<h2><%="#{current_user.level_type}: #{@name}" %></h2>
<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Station Name</th>
      <th>Address line 1</th>
      <th>Address line 2</th>
      <th>Pincode</th>
      <th>Contact Details</th>
      <th>Territory Id</th>
      <th>Region Id</th>
      <% if current_user.admin? %>
      <th>Edit</th>
      <% end %>
    </tr>
  </thead>
<% if current_user[:level_type]!=nil %>
  <% @stations.each do |station| %>
    <tr>
      <td><%=link_to station.nameStation, '#' %></td>
      <td><%=station.addr1 %></td>
      <td><%=station.addr2 %></td>
      <td><%=station.pincode %></td>
      <td><%=station.contactDetails %></td>
      <td><%=station.territory.idTerritory %></td>
      <td><%=station.territory.region.idRegion %></td>
      <% if current_user.admin? %>
      <td><%=link_to "edit", edit_station_path(station[:id]) %></td>
      <% end %>
    </tr>     
<% end %>
<% end %>

</table>

app/views/stations/new.html.erb
<% provide(:title, 'New Station') %>
<h1>New Station</h1>

<div class="row">
  <div class="span4 offset3">
    <%= form_for(@station) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
      <%= label_tag(:nameStation, "Station name:") %>
      <%= text_field_tag(:nameStation, @station.nameStation) %>

      <%= label_tag(:territory_id, "Territory:") %>
      <% territory_array = Territory.all.map { |territory| [territory.nameTerritory, territory.id]} %>
      <%= select_tag(:territory_id, options_for_select(territory_array, @station.territory_id)) %>

      <%= label_tag(:addr1, "Address line 1:") %>
      <%= text_field_tag(:addr1, @station.addr1) %>

      <%= label_tag(:addr2, "Address line 2:") %>
      <%= text_field_tag(:addr2, @station.addr2) %>

      <%= label_tag(:pincode, "Pincode:") %>
      <%= text_field_tag(:pincode, @station.pincode) %>

      <%= label_tag(:contactDetails, "Contact Details:") %>
      <%= text_field_tag(:contactDetails, @station.contactDetails) %>

      <%= f.submit "Create new Station", class: "btn  btn-primary" %>

    <% end %>
  </div>
</div>