config/routes.rb
Test2::Application.routes.draw do

  match '/initialise_sell_stock/:id', to: 'sell_stocks#initialise_sell_stock', via: 'get'
  match '/sell_stock', to: 'sell_stocks#sell_stock', via: 'post'
  match '/items/category_update', to: 'items#category_update', via: 'post'
  match '/items/edit_category/:id', to: 'items#edit_category', via: 'get'
  match '/items/list_category', to: 'items#list_category', via: 'get'
  match '/items/create_category', to: 'items#create_category', via: 'post'
  match '/items/new_category', to: 'items#new_category', via: 'get'
  match '/transfer_print', to: 'stocks#transfer_print', via: 'post'
  match '/transfer_comments/:id', to: 'stocks#transfer_comments', via: 'get'
  match '/stock_comments/:id', to: 'stocks#stock_comments', via: 'get'
  match '/alerts_lifecycle', to: 'stocks#alerts_lifecycle', via: 'get'
  match '/calculate_lifecycle_alerts', to: 'stocks#calculate_lifecycle_alerts', via: 'get'
  match '/alerts_minimum', to: 'stocks#alerts_minimum', via: 'get'
  match '/stations_cost', to: 'stocks#stations_cost', via: 'get'
  match '/total_costs', to: 'stocks#total_costs', via: 'get'
  match '/consumables/withdraw/:id', to: 'consumables#withdraw', via: 'get'
  match '/show_stock/:id', to: 'stocks#show_stock', via: 'get'
  match '/issueConsumable', to: 'consumables#issueConsumable', via: 'put'
  match '/consumable_issue/:id', to: 'consumables#consumable_issue', via: 'get'
  match '/station_transfers', to: 'stocks#station_transfers', via: 'get'
  match '/transfers_list', to: 'stocks#transfers_list', via: 'get'
  match '/initialise_transfer_stock/:id', to: 'stocks#initialise_transfer_stock', via: 'get'
  match '/transfer_stock', to: 'stocks#transfer_stock', via: 'post'
  match '/acknowledge_receipt_stock/:id', to: 'stocks#acknowledge_receipt_stock', via: 'get' 
  match '/assets/withdraw_asset/:id', to: 'assets#withdraw_asset', via: 'get'
  match '/assets/issued_list/:id', to: 'assets#issued_list', via: 'get'
  match '/issueAsset', to: 'assets#issueAsset', via: 'put'
  match '/assets/associate_list', to: 'assets#associate_list', via: 'get'
  resources :assets, only: [:destroy]
  match '/assets/issue_asset/:id', to: 'assets#issue_asset', via: 'get'
  match '/asset_list/:id', to: 'assets#asset_list', via: 'get'
  match '/present_stock_update', to: 'stocks#present_stock_update', via: 'put'
  match '/present_stock_edit/:id', to: 'stocks#present_stock_edit', via: 'get'
  match '/stocks/itemList', to: 'stocks#itemList', via: 'get'
  match '/stocks/categoryList', to: 'stocks#categoryList', via: 'get'
  match '/stocks/choice', to: 'stocks#choice', via: 'get'
  match '/associates/list', to: 'associates#list', via: 'get'
  match '/items/redirect', to: 'items#redirect', via: 'get'
  match '/items/list', to: 'items#list', via: 'get'
  resources :regions, :items, :territories, :vendors, :associates, :stocks

  resources :users
  resources :stations
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to:  'static_pages#home'
  
  match '/unassignedUser', to: 'users#assignUserform' ,via: 'get'
  match '/assignLevel', to: 'users#assignLevel' , via: 'put'
  match '/retainLevel/:id', to: 'users#retainLevel' , via: 'delete'
  match '/chooseLevel', to: 'users#chooseLevel' , via: 'get'
  match '/help', to: 'static_pages#help'
  match '/about',to: 'static_pages#about'
  match '/contact',to: 'static_pages#contact'

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	belongs_to :category
	has_many :items ,dependent: :nullify

	accepts_nested_attributes_for :items
	attr_accessible :nameVendor, :email, :phone, :category_id
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :nameVendor, presence: true, length: { maximum: 50 }
	validates :email, presence: true, format:     { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :phone, presence: true, length: { is: 10 }, numericality: true
	validate :ensure_category_exist

	private

		def ensure_category_exist
			if self.category_id.nil?
				true
			elsif Category.find(self.category_id).nil?
				errors.add(:category_id, 'not exist')
				false
			else
				true
			end
		end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
 	
 	before_filter :signed_in_user 
	before_filter :admin_user

  def index
		@vendors=Vendor.paginate(page: params[:page],per_page: 30)
	end

	def new
		@vendor = Vendor.new
	end

	def edit
		@vendor = Vendor.find(params[:id])
	end

	def update
		@vendor = Vendor.find(params[:id])
		if @vendor.update_attributes(nameVendor: params[:nameVendor], email: params[:email], phone: params[:phone], category_id: params[:category_id])
      flash[:success] = "Vendor updated"
      redirect_to vendors_path
    else
      render 'edit'
    end
	end

	def create
		@vendor = Vendor.new(nameVendor: params[:nameVendor], email: params[:email], phone: params[:phone], category_id: params[:category_id])
  	if @vendor.save
      flash[:success] = "Successfully added #{@vendor.nameVendor}"
      redirect_to vendors_path
    else
    	render 'new'
  	end
	end

	def destroy
    Vendor.find(params[:id]).destroy
    flash[:success] = "Vendor destroyed."
    redirect_to vendors_url
  end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/edit.html.erb
<% provide(:title, 'Edit vendor') %>
<h1>Edit vendor</h1>

<div class="row">
  <div class="span4 offset3">
    <%= form_for(@vendor) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag(:id, @vendor[:id]) %>

      <%= label_tag(:nameVendor, "Vendor name:")%>
      <%= text_field_tag(:nameVendor, @vendor.nameVendor) %>

      <%= label_tag(:email, "Email:") %>
      <%= text_field_tag(:email, @vendor.email )%>

      <%= label_tag(:phone, "Phone:") %>
      <%= number_field_tag(:phone, @vendor.phone) %>

      <%= label_tag(:category_id, "Category:") %>
      <%  @itemCategory = Category.all.map { |category| [category.nameCategory, category.id]}
          @itemCategory = [['All', nil]] + @itemCategory %>
      <%= select_tag(:category_id, options_for_select(@itemCategory, @vendor.category_id)) %>

      <%= f.submit "Edit vendor", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/vendors/index.html.erb
<% provide(:title, 'All vendors') %>
<h1>All vendors</h1>

<%= will_paginate @regions %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Vendor Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Category</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <% @vendors.each do |vendor| %>
    <tr>
      <td><%=vendor.nameVendor %></td>
      <td><%=vendor.email %></td>
      <td><%=vendor.phone %></td>
      <% if vendor.category_id != nil %>
      <td><%=vendor.category.nameCategory %></td>
      <% else %>
      <td><%='All' %></td>
      <% end %>
      <td><%=link_to "edit", edit_vendor_path(vendor[:id]) %></td>
      <td><%= link_to "delete ", vendor, method: :delete, data: { confirm: "You sure?" } %></td>
    </tr>     
  <% end %>

</table>

<%= will_paginate @regions %>

app/views/vendors/new.html.erb
<% provide(:title, 'Add vendor') %>
<h1>Add vendor</h1>

<div class="row">
  <div class="span4 offset3">
    <%= form_for(@vendor) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= label_tag(:nameVendor, "Vendor name:")%>
      <%= text_field_tag(:nameVendor, @vendor.nameVendor) %>

      <%= label_tag(:email, "Email:") %>
      <%= text_field_tag(:email, @vendor.email )%>

      <%= label_tag(:phone, "Phone:") %>
      <%= number_field_tag(:phone, @vendor.phone) %>

      <%= label_tag(:category_id, "Category:") %>
      <%  @itemCategory = Category.all.map { |category| [category.nameCategory, category.id]}
          @itemCategory = @itemCategory + [['All', nil]] %>
      <%= select_tag(:category_id, options_for_select(@itemCategory, @vendor.category_id)) %>

      <%= f.submit "Add vendor", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>