config/routes.rb
Test2::Application.routes.draw do

  match '/initialise_sell_stock/:id', to: 'sell_stocks#initialise_sell_stock', via: 'get'
  match '/sell_stock', to: 'sell_stocks#sell_stock', via: 'post'
  match '/items/category_update', to: 'items#category_update', via: 'post'
  match '/items/edit_category/:id', to: 'items#edit_category', via: 'get'
  match '/items/list_category', to: 'items#list_category', via: 'get'
  match '/items/create_category', to: 'items#create_category', via: 'post'
  match '/items/new_category', to: 'items#new_category', via: 'get'
  match '/transfer_print', to: 'stocks#transfer_print', via: 'post'
  match '/transfer_comments/:id', to: 'stocks#transfer_comments', via: 'get'
  match '/stock_comments/:id', to: 'stocks#stock_comments', via: 'get'
  match '/alerts_lifecycle', to: 'stocks#alerts_lifecycle', via: 'get'
  match '/calculate_lifecycle_alerts', to: 'stocks#calculate_lifecycle_alerts', via: 'get'
  match '/alerts_minimum', to: 'stocks#alerts_minimum', via: 'get'
  match '/stations_cost', to: 'stocks#stations_cost', via: 'get'
  match '/total_costs', to: 'stocks#total_costs', via: 'get'
  match '/consumables/withdraw/:id', to: 'consumables#withdraw', via: 'get'
  match '/show_stock/:id', to: 'stocks#show_stock', via: 'get'
  match '/issueConsumable', to: 'consumables#issueConsumable', via: 'put'
  match '/consumable_issue/:id', to: 'consumables#consumable_issue', via: 'get'
  match '/station_transfers', to: 'stocks#station_transfers', via: 'get'
  match '/transfers_list', to: 'stocks#transfers_list', via: 'get'
  match '/initialise_transfer_stock/:id', to: 'stocks#initialise_transfer_stock', via: 'get'
  match '/transfer_stock', to: 'stocks#transfer_stock', via: 'post'
  match '/acknowledge_receipt_stock/:id', to: 'stocks#acknowledge_receipt_stock', via: 'get' 
  match '/assets/withdraw_asset/:id', to: 'assets#withdraw_asset', via: 'get'
  match '/assets/issued_list/:id', to: 'assets#issued_list', via: 'get'
  match '/issueAsset', to: 'assets#issueAsset', via: 'put'
  match '/assets/associate_list', to: 'assets#associate_list', via: 'get'
  resources :assets, only: [:destroy]
  match '/assets/issue_asset/:id', to: 'assets#issue_asset', via: 'get'
  match '/asset_list/:id', to: 'assets#asset_list', via: 'get'
  match '/present_stock_update', to: 'stocks#present_stock_update', via: 'put'
  match '/present_stock_edit/:id', to: 'stocks#present_stock_edit', via: 'get'
  match '/stocks/itemList', to: 'stocks#itemList', via: 'get'
  match '/stocks/categoryList', to: 'stocks#categoryList', via: 'get'
  match '/stocks/choice', to: 'stocks#choice', via: 'get'
  match '/associates/list', to: 'associates#list', via: 'get'
  match '/items/redirect', to: 'items#redirect', via: 'get'
  match '/items/list', to: 'items#list', via: 'get'
  resources :regions, :items, :territories, :vendors, :associates, :stocks

  resources :users
  resources :stations
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to:  'static_pages#home'
  
  match '/unassignedUser', to: 'users#assignUserform' ,via: 'get'
  match '/assignLevel', to: 'users#assignLevel' , via: 'put'
  match '/retainLevel/:id', to: 'users#retainLevel' , via: 'delete'
  match '/chooseLevel', to: 'users#chooseLevel' , via: 'get'
  match '/help', to: 'static_pages#help'
  match '/about',to: 'static_pages#about'
  match '/contact',to: 'static_pages#contact'

end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
	belongs_to :vendor, validate: true
	has_many :stocks, dependent: :restrict

	attr_accessible :codeItem, :nameItem, :lifeCycle, :leadTime, :vendor_id, :minimumStock, :cost, :assetType, :category_id, :brand, :distinction, :model

	validate :ensure_vendor_exist
	validate :ensure_category_exist
	
	validates :codeItem, presence: true, length: { maximum: 10 }, uniqueness: true
	validates :nameItem, presence: true, length: { maximum: 50 }, uniqueness: true
	validates :cost , presence:true ,numericality: true
	validates :lifeCycle, presence: true, numericality: true
	validates :leadTime, presence: true, numericality: true
	validates :minimumStock, presence: true, numericality: true
	validates :assetType, presence: true, length: { maximum: 15 }
	validates :category_id, presence: true
	validates :brand, presence: true, length: { maximum: 50 }
	validates :distinction, length: { maximum: 50 }
	validates :model, length: { maximum: 50}

	
	private

		def ensure_vendor_exist
			if self.vendor_id.nil?
				true
			elsif Vendor.find(self.vendor_id).nil?
				errors.add(:vendor_id, 'not exist')
				false
			else
				true
			end
		end

		def ensure_category_exist
			if self.category_id.nil?
				true
			elsif Category.find(self.category_id).nil?
				errors.add(:category_id, 'not exist')
				false
			else
				true
			end
		end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_filter :signed_in_user 
	before_filter :admin_user, except: [:index, :list]

  def index
  	@itemCategory = categoryList
  end

  def new
    @item = Item.new
  	@itemCategory = Category.all.map { |category| [category.nameCategory, category.nameCategory]}
  end

  def edit
    @item = Item.find(params[:id])
    @category = @item.category.nameCategory
  end

  def update
    @lifeCycle = params[:lifeCycle].to_i.send(params[:lifeCycleType]).to_i
    @leadTime = params[:leadTime].to_i.send(params[:leadTimeType]).to_i

    item_hash = {nameItem: params[:item][:nameItem], codeItem: params[:item][:codeItem], cost: params[:item][:cost], lifeCycle: @lifeCycle, leadTime: @leadTime,minimumStock: params[:item][:minimumStock], assetType: params[:item][:assetType], vendor_id: params[:item][:vendor_id] , brand: params[:item][:brand], distinction: params[:item][:distinction], model: params[:item][:model]}

    @itemCategory = Category.all.map { |category| [category.nameCategory, category.nameCategory]}
    @item = Item.find(params[:id])
    @category = @item.category.nameCategory

    @item.assign_attributes(item_hash)
    if @item.valid?
      @item.save
      flash[:success] = "Item updated"
      redirect_to items_path
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.stocks != nil
      flash[:notice] = "Since stock of this item exist it cannot be deleted"
    else
      @item.destroy
      flash[:success] = "Item deleted."
    end
    redirect_to items_url
  end

  def redirect
    @item = Item.new
  	@category = params[:category]
    respond_to do |format|
      format.js
    end
  end

  def create
    @lifeCycle = params[:lifeCycle].to_i.send(params[:lifeCycleType]).to_i
    @leadTime = params[:leadTime].to_i.send(params[:leadTimeType]).to_i

    item_hash = {nameItem: params[:item][:nameItem], codeItem: params[:item][:codeItem], cost: params[:item][:cost], lifeCycle: @lifeCycle, leadTime: @leadTime,minimumStock: params[:item][:minimumStock], assetType: params[:item][:assetType], vendor_id: params[:item][:vendor_id] , brand: params[:item][:brand], distinction: params[:item][:distinction], model: params[:item][:model]}
    @itemCategory = Category.all.map { |category| [category.nameCategory, category.nameCategory]}

    @item = Category.find_by_nameCategory(params[:category]).items.new(item_hash)
    if @item.valid?
        flash[:sucess] = "Item added"
        @item.save
        redirect_to items_path
    else
      render 'new'
    end
  end

  def list
    @category = params[:category]
    if @category != 'All'
      @list = Category.find_by_nameCategory(@category).items
    else
      @list = Item.all
    end
    respond_to do |format|
      format.js
    end
  end

  def new_category
    @category = Category.new
  end

  def create_category
    if Category.create(nameCategory: params[:category][:nameCategory])
      flash[:success] = "Category created"
      redirect_to '/items/list_category'
    else
      flash[:error] = "Category name should be less than 30 characters"
      render 'new_category'
    end
    
  end

  def list_category
    @list = Category.all
  end

  def edit_category
    @category = Category.find(params[:id])
  end

  def category_update
    @category = Category.find(params[:id])
    @category.nameCategory = params[:nameCategory]
    if @category.save
      flash[:success] = "Category updated"
      redirect_to '/items/list_category'
    else
      flash[:error] = "Category name should be less than 30 characters"
      render 'edit_category'
    end
    
  end
end

app/helpers/items_helper.rb
module ItemsHelper

	def categoryList
		@itemCategory = Category.all.map { |category| [category.nameCategory, category.nameCategory]}
    @itemCategory = @itemCategory + [['All', 'All']]
  end
end

app/views/items/_list.html.erb
<table class="table table-striped table-bordered table-condensed">
  <caption>List</caption>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Distinction</th>
      <% if current_user.admin? %>
      <th>Cost per item</th>
      <% end %>
      <th>Life Cycle</th>
      <th>Lead Time</th>
      <th>Minimum Stock</th>
      <th>Asset Type</th>
      <th>Vendor</th>
      <% if current_user.admin? %>
      <th>Edit</th>
      <th>Delete</th>
      <% end %>
    </tr>
  </thead>
<% if @list!=nil %>
  <% @list.each do |list| %>
    <tr>
      <td><%= list.codeItem %></td>
      <td><%= list.nameItem %></td>
      <td><%= list.brand %></td>
      <td><%= list.model %></td>
      <td><%= list.distinction %></td>
      <% if current_user.admin? %>
      <td><%= list.cost %></td>
      <% end %>
      <td><%= toSensibleWords(toSensibleTime(list.lifeCycle)) %></td>
      <td><%= toSensibleWords(toSensibleTime(list.leadTime)) %></td>
      <td><%= list.minimumStock %></td>
      <td><%= list.assetType.capitalize %></td>
      <td><%= if list.vendor != nil
                list.vendor.nameVendor
              else 
                'No vendor'
              end
          %>
      </td>      
        <% if current_user.admin? %>
      <td><%=link_to "edit", edit_item_path(list[:id]) %></td>
      <td><%= link_to "delete ", list, method: :delete, data: { confirm: "You sure?" } %></td>
      <% end %>
    </tr>     
  <% end %>
<% end %>

</table>

app/views/items/_newForm.html.erb
<div class="row">
  <div class="span5 offset3">
    <%= form_for(@item) do |f| %>
      <%= hidden_field_tag(:category, @category) %>

      <%= f.label :code %>
      <%= f.text_field :codeItem %>

      <%= f.label :name %>
      <%= f.text_field :nameItem %>

      <%= f.label 'Cost Per Item' %>
      <%= f.text_field :cost, step: 1 %>

      <%= label_tag(:lifeCycle, "Life Cycle") %>
      <%= timePeriod('lifeCycle', toInsensibleTime(@item.lifeCycle)[:value], false) %>
      <%= timePeriodType('lifeCycle', toInsensibleTime(@item.lifeCycle)[:period], false) %>

      <%= label_tag(:leadTime, "Lead Time") %>
      <%= timePeriod('leadTime', toInsensibleTime(@item.leadTime)[:value], false) %>
      <%= timePeriodType('leadTime', toInsensibleTime(@item.leadTime)[:period], false) %>

      <%= f.label 'Minimum Stock' %>
      <%= f.text_field :minimumStock %>

      <%= f.label 'Asset Type' %>
      <% type = [['Fixed', 'fixed'], ['Consumable', 'consumable']] %>
      <%= f.select :assetType, type %>

      <%= f.label 'Vendor' %>
      <%  if @category == 'All'
            vendors = Vendor.all.map { |vendor| [vendor.nameVendor, vendor_id]}
          else 
            vendors_list = Category.find_by_nameCategory(@category).vendors + Vendor.where(category_id: nil)
            vendors = vendors_list.map { |vendor| [vendor.nameVendor, vendor.id]} 
          end
      %>
      <%= f.select :vendor_id, vendors %>

      <%= f.label :brand %>
      <%= f.text_field :brand %>

      <%= f.label :model %>
      <%= f.text_field :model %>      

      <%= f.label :distinction %>
      <%= f.text_field :distinction %>
   
      <%= f.submit "Create new Item", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/edit.html.erb
<% provide(:title, 'Edit Item') %>
<h1>Edit Item</h1>

<div class="row">
  <div class="span5 offset3">
    <%= form_for(@item) do |f| %>
    
      <%= render 'shared/error_messages', object: @item %>

      <%= hidden_field_tag(:category, @category) %>
      <%= hidden_field_tag(:id, @item.id) %>

      <%= f.label :code %>
      <%= f.text_field :codeItem %>

      <%= f.label :name %>
      <%= f.text_field :nameItem %>

      <%= f.label :cost, 'Cost Per Item' %>
      <%= f.text_field :cost, step: 1 %>

      <%= label_tag(:lifeCycle, "Life Cycle") %>
      <%= timePeriod('lifeCycle', toInsensibleTime(@item.lifeCycle)[:value], false) %>
      <%= timePeriodType('lifeCycle', toInsensibleTime(@item.lifeCycle)[:period], false) %>

      <%= label_tag(:leadTime, "Lead Time") %>
      <%= timePeriod('leadTime', toInsensibleTime(@item.leadTime)[:value], false) %>
      <%= timePeriodType('leadTime', toInsensibleTime(@item.leadTime)[:period], false) %>

      <%= f.label :minimumStock, 'Minimum Stock' %>
      <%= f.text_field :minimumStock %>

      <%= f.label 'Asset Type' %>
      <% type = [['Fixed', 'fixed'], ['Consumable', 'consumable']] %>
      <%= f.select :assetType, type %>

      <%= f.label 'Vendor' %>
      <%  if @category == 'All'
            vendors = Vendor.all.map { |vendor| [vendor.nameVendor, vendor_id]}
          else 
            vendors_list = Category.find_by_nameCategory(@category).vendors + Vendor.where(category_id: nil)
            vendors = vendors_list.map { |vendor| [vendor.nameVendor, vendor.id]} 
          end
      %>
      <%= f.select :vendor_id, vendors %>

      <%= f.label :brand %>
      <%= f.text_field :brand %>

      <%= f.label :model %>
      <%= f.text_field :model %>      

      <%= f.label :distinction %>
      <%= f.text_field :distinction %>
   
      <%= f.submit "Edit Item", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/edit_category.html.erb
<% provide(:title, 'Edit Category') %>
<h1>Edit Category</h1>

<div class="row">
  <div class="span5 offset3">
    <%= form_tag('/items/category_update') do |f| %>

    	<%= hidden_field_tag(:id, @category[:id]) %>

      <%= label_tag :name %>
      <%= text_field_tag :nameCategory , @category.nameCategory%>

      <%= submit_tag "Update Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'Items') %>
<h1>Items</h1>

<div class="row">
  <div class="span4 offset4">
  	
    <%= form_tag("/items/list", method: :get, remote: true) do %>

      <%= label_tag(:category, "Category:") %>
      <%= select_tag(:category, options_for_select(@itemCategory)) %>

      <%= submit_tag "Select a category", class: "btn  btn-primary" %>
  	<% end %>
  </div>
</div>

<div id="item_details">
</div>

<div id="category_list">        
</div>

app/views/items/list.js.erb
$("#category_list").html("<%= escape_javascript(render('items/list')) %>")

app/views/items/list_category.html.erb
<% provide(:title, 'Categories') %>
<h1>Categories</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Edit</th>
    </tr>
  </thead>
<% if @list!=nil %>
  <% @list.each do |list| %>
    <tr>
      <td><%= list.nameCategory %></td>
      <td><%=link_to "edit", "/items/edit_category/#{list.id}" %></td>
    </tr>     
  <% end %>
<% end %>

</table>

app/views/items/new.html.erb
<% provide(:title, 'New Item') %>
<h1>New Item</h1>

<div class="row">
  <div class="span4 offset4">
  	<% if @item!=nil %>
  		<%= render 'shared/error_messages', object: @item %>
  	<% end %>
  	
    <%= form_tag("/items/redirect", method: :get, remote: true) do %>

      <%= label_tag(:category, "Category:") %>
      <%= select_tag(:category, options_for_select(@itemCategory)) %>

      <%= submit_tag "Select a category", class: "btn  btn-primary" %>
  	<% end %>
  </div>
</div>

<div id="category_form">        
</div>

app/views/items/new_category.html.erb
<% provide(:title, 'New Category') %>
<h1>New Category</h1>

<div class="row">
  <div class="span5 offset3">
    <%= form_for(@category, url: '/items/create_category') do |f| %>

      <%= f.label :name %>
      <%= f.text_field :nameCategory %>

      <%= f.submit "Create new Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/redirect.js.erb
$("#category_form").html("<%= escape_javascript(render('items/newForm')) %>")