config/routes.rb
Test2::Application.routes.draw do

  match '/initialise_sell_stock/:id', to: 'sell_stocks#initialise_sell_stock', via: 'get'
  match '/sell_stock', to: 'sell_stocks#sell_stock', via: 'post'
  match '/items/category_update', to: 'items#category_update', via: 'post'
  match '/items/edit_category/:id', to: 'items#edit_category', via: 'get'
  match '/items/list_category', to: 'items#list_category', via: 'get'
  match '/items/create_category', to: 'items#create_category', via: 'post'
  match '/items/new_category', to: 'items#new_category', via: 'get'
  match '/transfer_print', to: 'stocks#transfer_print', via: 'post'
  match '/transfer_comments/:id', to: 'stocks#transfer_comments', via: 'get'
  match '/stock_comments/:id', to: 'stocks#stock_comments', via: 'get'
  match '/alerts_lifecycle', to: 'stocks#alerts_lifecycle', via: 'get'
  match '/calculate_lifecycle_alerts', to: 'stocks#calculate_lifecycle_alerts', via: 'get'
  match '/alerts_minimum', to: 'stocks#alerts_minimum', via: 'get'
  match '/stations_cost', to: 'stocks#stations_cost', via: 'get'
  match '/total_costs', to: 'stocks#total_costs', via: 'get'
  match '/consumables/withdraw/:id', to: 'consumables#withdraw', via: 'get'
  match '/show_stock/:id', to: 'stocks#show_stock', via: 'get'
  match '/issueConsumable', to: 'consumables#issueConsumable', via: 'put'
  match '/consumable_issue/:id', to: 'consumables#consumable_issue', via: 'get'
  match '/station_transfers', to: 'stocks#station_transfers', via: 'get'
  match '/transfers_list', to: 'stocks#transfers_list', via: 'get'
  match '/initialise_transfer_stock/:id', to: 'stocks#initialise_transfer_stock', via: 'get'
  match '/transfer_stock', to: 'stocks#transfer_stock', via: 'post'
  match '/acknowledge_receipt_stock/:id', to: 'stocks#acknowledge_receipt_stock', via: 'get' 
  match '/assets/withdraw_asset/:id', to: 'assets#withdraw_asset', via: 'get'
  match '/assets/issued_list/:id', to: 'assets#issued_list', via: 'get'
  match '/issueAsset', to: 'assets#issueAsset', via: 'put'
  match '/assets/associate_list', to: 'assets#associate_list', via: 'get'
  resources :assets, only: [:destroy]
  match '/assets/issue_asset/:id', to: 'assets#issue_asset', via: 'get'
  match '/asset_list/:id', to: 'assets#asset_list', via: 'get'
  match '/present_stock_update', to: 'stocks#present_stock_update', via: 'put'
  match '/present_stock_edit/:id', to: 'stocks#present_stock_edit', via: 'get'
  match '/stocks/itemList', to: 'stocks#itemList', via: 'get'
  match '/stocks/categoryList', to: 'stocks#categoryList', via: 'get'
  match '/stocks/choice', to: 'stocks#choice', via: 'get'
  match '/associates/list', to: 'associates#list', via: 'get'
  match '/items/redirect', to: 'items#redirect', via: 'get'
  match '/items/list', to: 'items#list', via: 'get'
  resources :regions, :items, :territories, :vendors, :associates, :stocks

  resources :users
  resources :stations
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root to:  'static_pages#home'
  
  match '/unassignedUser', to: 'users#assignUserform' ,via: 'get'
  match '/assignLevel', to: 'users#assignLevel' , via: 'put'
  match '/retainLevel/:id', to: 'users#retainLevel' , via: 'delete'
  match '/chooseLevel', to: 'users#chooseLevel' , via: 'get'
  match '/help', to: 'static_pages#help'
  match '/about',to: 'static_pages#about'
  match '/contact',to: 'static_pages#contact'

end

app/models/associate.rb
class Associate < ActiveRecord::Base
  belongs_to :station
  before_save { self.email = email.downcase }
  has_many :issued_items, dependent: :delete_all
  has_many :issued_consumables, dependent: :delete_all
  has_many :assets, through: :issued_items

  accepts_nested_attributes_for :issued_items, :issued_consumables
  before_save { self.email = email.downcase }
  attr_accessible :name, :email, :dateOfJoining, :station_id 

  validate :ensure_station_exist
  validates :name , presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :dateOfJoining, presence: {:message => 'is Bank/invalid'}
  validates :station_id, presence: true	
  validate :date_is_not_in_future

  private

   def ensure_station_exist
      if Station.find(self.station_id).nil?
        errors.add(:station_id, 'Station does not exist')
        false
      else
        true
      end
    end

  def date_is_not_in_future
    if self.dateOfJoining > Date.today
      errors.add(:dateOfJoining, 'cannot be in future')
      false
    else
      true
    end
  end
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
	before_filter :signed_in_user
  before_filter :atleast_one_station

  def new
  	@associate=Associate.new
  end

  def edit
    @associate = Associate.find(params[:id])
    if can_access_station(@associate.station) == false
      return
    end
  end

  def update
		@associate = Associate.find(params[:id])
    if can_access_station(@associate.station) == false
      return
    end
		begin
  		@date= Date.new(params[:associate][:'dateOfJoining(1i)'].to_i, params[:associate][:'dateOfJoining(2i)'].to_i, params[:associate][:'dateOfJoining(3i)'].to_i)
  	rescue ArgumentError
  		@date=nil
  	end
		if @associate.update_attributes(name: params[:name], email: params[:email], dateOfJoining: @date, station_id: params[:station_id])
      flash[:success] = "Associate updated"
      redirect_to associates_path
    else
      render 'edit'
    end
	end

  def create
    if can_access_station(Station.find(params[:station_id])) == false
      return
    end
  	begin
  		@date= Date.new(params[:associate][:'dateOfJoining(1i)'].to_i, params[:associate][:'dateOfJoining(2i)'].to_i, params[:associate][:'dateOfJoining(3i)'].to_i)
  	rescue ArgumentError
  		@date=nil
  	end
  	@associate = Associate.new(name: params[:name], email: params[:email], station_id: params[:station_id], dateOfJoining: @date)
    	
  	if @associate.save
      flash[:success] = "Successfully added #{@associate.name}"
      redirect_to associates_path
    else
    	render 'new'
  	end
	end

	def index
		@stations = user_access_stations(current_user)
		@stationList = @stations[:stations].map { |station| [station.nameStation, station.id]}
	end

	def list
    @station = Station.find(params[:station])
    if can_access_station(@station) == false
      return
    end
    @associates = @station.associates
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @associate = Associate.find(params[:id])
    if can_access_station(@associate.station) == false
      return
    end
    @assets = @associate.assets
    @assets.each do |asset|
      asset.issued = false
      @stock = asset.stock
      @stock.presentStock = @stock.presentStock + 1
      @stock.save
      @asset.save
    end
    @associate.destroy
    flash[:success] = "Associate destroyed , issued items retained and stock updated"
    redirect_to associates_url
  end

end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_list.html.erb
<table class="table table-striped table-bordered table-condensed">
  <caption> Associates</caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date Of Joinin</th>
      <th>Issued Items</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
<% if @associates!=nil %>
  <% @associates.each do |associate| %>
    <tr>
      <td><%= associate.name%></td>
      <td><%= associate.email %></td>
      <td><%= associate.dateOfJoining.strftime('%d/%m/%Y') %></td>
      <td><%= link_to "Issued Items", "/assets/issued_list/#{associate.id}" %></th>
      <td><%=link_to "edit", edit_associate_path(associate.id) %></td>
      <td><%= link_to "delete ", associate, method: :delete, data: { confirm: "You sure?" } %></td>
    </tr>     
  <% end %>
<% end %>

</table>

app/views/associates/edit.html.erb
<% provide(:title, 'Edit associate') %>
<h1>Edit associate</h1> 

<div class="row">
  <div class="span4 offset3">
    <%= form_for(@associate) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag(:id, @associate.id) %>

      <%= label_tag(:station_id, "Station:") %>
      <% result = user_access_stations(current_user) %>
      <%= select_tag(:station_id, options_from_collection_for_select(result[:stations], "id","nameStation", @associate.station_id)) %>

      <%= label_tag(:name, "Associate name:") %>
      <%= text_field_tag(:name, @associate.name) %>

      <%= label_tag(:email, "Email:") %>
      <%= text_field_tag(:email, @associate.email) %>

      <%= label_tag(:dateOfJoining, "Date of Joining:") %>
      <%= date_select(:associate,:dateOfJoining, :order => [:day, :month, :year], :start_year => Time.now.year - 20, :end_year => Time.now.year, default: {day: @associate.dateOfJoining} ) %>

      <%= f.submit "Edit associate", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/associates/index.html.erb
<% provide(:title, 'Associates') %>
<h1>Associates</h1>

<div class="row">
  <div class="span4 offset4">
  	
    <%= form_tag("/associates/list", method: :get, remote: true) do %>

      <%= label_tag(:station, "Station:") %>
      <%= select_tag(:station, options_for_select(@stationList)) %>

      <%= submit_tag "Select a station", class: "btn  btn-primary" %>
  	<% end %>
  </div>
</div>

<div id="associate_list">        
</div>

app/views/associates/list.js.erb
$("#associate_list").html("<%= escape_javascript(render('associates/list')) %>")

app/views/associates/new.html.erb
<% provide(:title, 'Add associate') %>
<h1>Add associate</h1> 

<div class="row">
  <div class="span4 offset3">
    <%= form_for(@associate) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= label_tag(:station_id, "Station:") %>
      <% result = user_access_stations(current_user) %>
      <%= select_tag(:station_id, options_from_collection_for_select(result[:stations], "id","nameStation", @associate.station_id)) %>

      <%= label_tag(:name, "Associate name:") %>
      <%= text_field_tag(:name, @associate.name) %>

      <%= label_tag(:email, "Email:") %>
      <%= text_field_tag(:email, @associate.email) %>

      <%= label_tag(:dateOfJoining, "Date of Joining:") %>
      <%= date_select(:associate,:dateOfJoining, :order => [:day, :month, :year], :start_year => Time.now.year - 20, :end_year => Time.now.year, default: {day: @associate.dateOfJoining}) %>

      <%= f.submit "Add associate", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>